modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="https://github.com/MasterGeneral156/CTD-Mythos/blob/1.12/LICENSE"
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Mythos/issues"
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]] #mandatory
modId="mythosreborn" #mandatory
version="2.0-dev #mandatory
displayName="Mythos Reborn" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/CTD-Mythos.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/ctd-mythos" #optional
#logoFile="examplemod.png" #optional
authors="TheMasterGeneral" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

# The description text for the mod (multi line!) (#mandatory)
description='''CTD Mythos, but reborn!'''
[[dependencies.mythosreborn]]
    modId="ctdcore"
    mandatory=true
    versionRange="[2.3,]"
    ordering="NONE"
    side="BOTH"